
const techIcons:any = {
    "C#": "devicon-csharp-plain",
    "Node.js": "devicon-nodejs-plain",
    "Pawn": "devicon-pawn-plain",
    "VB6": "devicon-visualstudio-plain",
    "VB.Net": "devicon-visualstudio-plain",
    "Java": "devicon-java-plain",
    "JavaScript": "devicon-javascript-plain",
    "PHP": "devicon-php-plain",
    "Vue.js": "devicon-vuejs-plain",
    "Laravel": "devicon-laravel-plain",
    "jQuery": "devicon-jquery-plain",
    "Bootstrap": "devicon-bootstrap-plain",
    "TailwindCSS": "devicon-tailwindcss-plain",
    "TypeScript": "devicon-typescript-plain",
    "Express.js": "devicon-express-original",
    ".NET": "devicon-dotnet-plain",
    "React": "devicon-react-original",
    "Next.js": "devicon-nextjs-original",
    "MySQL": "devicon-mysql-plain",
    "SQLite": "devicon-sqlite-plain",
    "MSSQL": "devicon-mssql-plain",
    "DynamoDB": "devicon-dynamodb-plain",
    "HTML5": "devicon-html5-plain",
    "CSS3": "devicon-css3-plain",
    "Bitbucket": "devicon-bitbucket-plain",
    "Jira": "devicon-jira-plain",
    "Trello": "devicon-trello-plain",
    "GitHub": "devicon-github-plain",
    "Git": "devicon-git-plain",
    "Adobe Photoshop": "devicon-photoshop-plain",
    "Adobe Premiere": "devicon-premiere-plain",
    "AWS": "devicon-amazonwebservices-original",
    "OVH Cloud": "devicon-ovh-plain",
    "GitHub CI/CD": "devicon-github-plain",
  };

  export default techIcons;